#! /bin/csh -f

foreach temp (2.0)
  echo " --- temp ${temp} "  	
  echo " --- temp ${temp} "  	>> out
  cat > fort.15  <<endofdata
  ibeg  , nequil  , lmax   nsamp  iseed
   0      1000      10000    1    48573478
  dr      vmax  succ
  0.09    0.01   50.
  ndispl  nvol nswap  nrot
  200      2    10  200
npart temp rho      p       lattice  latdirection,  bondtype
512   ${temp} .32   32    'cubic'    "x"          "fixed"
rv
3.0 
endofdata
 cp lj.res			fort.11
  cp lj.model		fort.25
 time  ../Source/Gibbs  >>&	out 
 cp fort.21		lj.res
 mv fort.66		lj.prt
 cat fort.44     >>		lj.xy
 #perform block analysis
  cp lj.prt data
  cp lj.prth		fort.31
  mv  lj.prt		fort.32
 ../Block/block    >>	out 
 rm fort.*
end
exit
